#!/bin/zsh

STATUS=$(playerctl status)

# Otherwise
TITLE=$(playerctl metadata title 2>/dev/null)
ARTIST=$(playerctl metadata artist 2>/dev/null)
ALBUM=$(playerctl metadata album 2>/dev/null)
TRACK=$(playerctl metadata trackNumber 2>/dev/null)
BITRATE=$(playerctl metadata bitrate 2>/dev/null)
LENGTH=$(playerctl metadata length 2>/dev/null)
RAW=$(playerctl metadata)

printf "
Status: $STATUS
Title: $TITLE
Artist: $ARTIST
Album: $ALBUM
Track Number: $TRACK
Bitrate: $BITRATE
Length $LENGTH bytes

Raw playerctl data...
$RAW
"
