-- This file has been generated by notion. Do not edit.
return {
    [1] = {
        ["managed"] = {
            [1] = {
                ["level"] = 0.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["name"] = "WGroupWS<1>",
                ["initial_outputs"] = {
                    [1] = "HDMI-0",
                },
                ["hidden"] = true,
                ["managed"] = {
                },
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["level"] = 0.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["name"] = "WGroupWS<3>",
                ["initial_outputs"] = {
                    [1] = "HDMI-0",
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 1920.0,
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["name"] = "Tiling Frame",
                                ["managed"] = {
                                    [1] = {
                                        ["level"] = 0.0,
                                        ["geom"] = {
                                            ["h"] = 1898.0,
                                            ["y"] = 21.0,
                                            ["x"] = 1.0,
                                            ["w"] = 1078.0,
                                        },
                                        ["type"] = "WGroupCW",
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["windowid"] = 8388619.0,
                                                ["geom"] = {
                                                    ["h"] = 1898.0,
                                                    ["y"] = 0.0,
                                                    ["x"] = 0.0,
                                                    ["w"] = 1078.0,
                                                },
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["level"] = 0.0,
                                                ["sizepolicy"] = "full",
                                                ["checkcode"] = 4.0,
                                            },
                                        },
                                        ["switchto"] = true,
                                        ["name"] = "WGroupCW<1>",
                                    },
                                },
                                ["type"] = "WFrame",
                                ["mode"] = 1.0,
                            },
                        },
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<3>",
                    },
                },
                ["switchto"] = true,
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*",
                ["unnumbered"] = true,
            },
            [4] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<2>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<2>",
                ["unnumbered"] = true,
            },
            [5] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<3>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<3>",
                ["unnumbered"] = true,
            },
            [6] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<4>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<4>",
                ["unnumbered"] = true,
            },
            [7] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<5>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<5>",
                ["unnumbered"] = true,
            },
            [8] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<6>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<6>",
                ["unnumbered"] = true,
            },
            [9] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<7>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<7>",
                ["unnumbered"] = true,
            },
            [10] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 320.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<8>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<8>",
                ["unnumbered"] = true,
            },
            [11] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<9>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<9>",
                ["unnumbered"] = true,
            },
            [12] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<10>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<10>",
                ["unnumbered"] = true,
            },
            [13] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<11>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<11>",
                ["unnumbered"] = true,
            },
            [14] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<12>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<12>",
                ["unnumbered"] = true,
            },
            [15] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<13>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<13>",
                ["unnumbered"] = true,
            },
            [16] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<14>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<14>",
                ["unnumbered"] = true,
            },
            [17] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<15>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<15>",
                ["unnumbered"] = true,
            },
            [18] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<16>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<16>",
                ["unnumbered"] = true,
            },
            [19] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<17>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<17>",
                ["unnumbered"] = true,
            },
            [20] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<18>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<18>",
                ["unnumbered"] = true,
            },
            [21] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<19>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<19>",
                ["unnumbered"] = true,
            },
            [22] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<20>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<20>",
                ["unnumbered"] = true,
            },
            [23] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<21>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<21>",
                ["unnumbered"] = true,
            },
            [24] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<22>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<22>",
                ["unnumbered"] = true,
            },
            [25] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<23>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<23>",
                ["unnumbered"] = true,
            },
            [26] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<24>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<24>",
                ["unnumbered"] = true,
            },
            [27] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<25>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<25>",
                ["unnumbered"] = true,
            },
            [28] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<26>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<26>",
                ["unnumbered"] = true,
            },
            [29] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 560.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<27>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<27>",
                ["unnumbered"] = true,
            },
            [30] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1920.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1080.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 140.0,
                            ["x"] = 0.0,
                            ["w"] = 1080.0,
                        },
                        ["name"] = "*scratchpad*<28>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<28>",
                ["unnumbered"] = true,
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen<1>",
    },
    [0] = {
        ["managed"] = {
            [1] = {
                ["level"] = 0.0,
                ["geom"] = {
                    ["h"] = 1440.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 2560.0,
                },
                ["name"] = "M0",
                ["initial_outputs"] = {
                    [1] = "DP-0",
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 1440.0,
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 2560.0,
                        },
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "Framed PHolder Frame",
                                    ["managed"] = {
                                        [1] = {
                                            ["level"] = 0.0,
                                            ["geom"] = {
                                                ["h"] = 1416.0,
                                                ["y"] = 21.0,
                                                ["x"] = 1.0,
                                                ["w"] = 2558.0,
                                            },
                                            ["type"] = "WGroupCW",
                                            ["hidden"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["windowid"] = 4194349.0,
                                                    ["geom"] = {
                                                        ["h"] = 1416.0,
                                                        ["y"] = 0.0,
                                                        ["x"] = 0.0,
                                                        ["w"] = 2558.0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 0.0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 1.0,
                                                },
                                            },
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW",
                                        },
                                        [2] = {
                                            ["level"] = 0.0,
                                            ["geom"] = {
                                                ["h"] = 1416.0,
                                                ["y"] = 21.0,
                                                ["x"] = 1.0,
                                                ["w"] = 2558.0,
                                            },
                                            ["type"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["windowid"] = 58720267.0,
                                                    ["geom"] = {
                                                        ["h"] = 1416.0,
                                                        ["y"] = 0.0,
                                                        ["x"] = 0.0,
                                                        ["w"] = 2558.0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 0.0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 2.0,
                                                },
                                            },
                                            ["switchto"] = true,
                                            ["name"] = "WGroupCW<3>",
                                        },
                                        [3] = {
                                            ["level"] = 0.0,
                                            ["geom"] = {
                                                ["h"] = 1416.0,
                                                ["y"] = 21.0,
                                                ["x"] = 1.0,
                                                ["w"] = 2558.0,
                                            },
                                            ["type"] = "WGroupCW",
                                            ["hidden"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["windowid"] = 14680075.0,
                                                    ["geom"] = {
                                                        ["h"] = 1416.0,
                                                        ["y"] = 0.0,
                                                        ["x"] = 0.0,
                                                        ["w"] = 2558.0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 0.0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 3.0,
                                                },
                                            },
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<2>",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                },
                            },
                            ["tls"] = 1438.0,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 2.0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                        },
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<1>",
                    },
                },
                ["switchto"] = true,
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["level"] = 0.0,
                ["geom"] = {
                    ["h"] = 1440.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 2560.0,
                },
                ["name"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "DP-0",
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 1440.0,
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 2560.0,
                        },
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "WFrame",
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                },
                            },
                            ["tls"] = 1280.0,
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "WFrame<1>",
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                },
                            },
                            ["brs"] = 1280.0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                        },
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling",
                    },
                },
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["level"] = 0.0,
                ["geom"] = {
                    ["h"] = 1440.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 2560.0,
                },
                ["name"] = "WGroupWS<2>",
                ["initial_outputs"] = {
                    [1] = "DP-0",
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["h"] = 1440.0,
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 2560.0,
                        },
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "WFrame<2>",
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                },
                            },
                            ["tls"] = 1280.0,
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["name"] = "WFrame<3>",
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                },
                            },
                            ["brs"] = 1280.0,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                        },
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<2>",
                    },
                },
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
            },
            [4] = {
                ["level"] = 1.0,
                ["geom"] = {
                    ["h"] = 1440.0,
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 2560.0,
                },
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["level"] = 1024.0,
                        ["geom"] = {
                            ["h"] = 800.0,
                            ["y"] = 140.0,
                            ["x"] = 260.0,
                            ["w"] = 1400.0,
                        },
                        ["name"] = "*scratchpad*<1>",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*<1>",
                ["unnumbered"] = true,
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen",
    },
}

