-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 768.0,
                    ["w"] = 1024.0,
                    ["x"] = 0.0,
                },
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                },
                ["name"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 768.0,
                            ["w"] = 1024.0,
                            ["x"] = 0.0,
                        },
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["brs"] = 512.0,
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["name"] = "Tiling Frame<1>",
                                    ["managed"] = {
                                        [1] = {
                                            ["geom"] = {
                                                ["y"] = 19.0,
                                                ["h"] = 748.0,
                                                ["w"] = 510.0,
                                                ["x"] = 1.0,
                                            },
                                            ["hidden"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["y"] = 2.0,
                                                        ["h"] = 745.0,
                                                        ["w"] = 508.0,
                                                        ["x"] = 1.0,
                                                    },
                                                    ["checkcode"] = 2.0,
                                                    ["level"] = 0.0,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 4194316.0,
                                                    ["bottom"] = true,
                                                    ["sizepolicy"] = "full",
                                                },
                                            },
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0.0,
                                            ["name"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                        },
                                        [2] = {
                                            ["geom"] = {
                                                ["y"] = 19.0,
                                                ["h"] = 748.0,
                                                ["w"] = 510.0,
                                                ["x"] = 1.0,
                                            },
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["y"] = 2.0,
                                                        ["h"] = 745.0,
                                                        ["w"] = 508.0,
                                                        ["x"] = 1.0,
                                                    },
                                                    ["checkcode"] = 3.0,
                                                    ["level"] = 0.0,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 8388620.0,
                                                    ["bottom"] = true,
                                                    ["sizepolicy"] = "full",
                                                },
                                            },
                                            ["sizepolicy"] = "full",
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0.0,
                                            ["name"] = "WGroupCW<2>",
                                            ["switchto"] = true,
                                        },
                                    },
                                },
                            },
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                            ["tls"] = 512.0,
                            ["tl"] = {
                                ["brs"] = 15.0,
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["type"] = "WSplitSplit",
                                ["dir"] = "vertical",
                                ["tls"] = 753.0,
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1.0,
                                        ["name"] = "Tiling Frame",
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["y"] = 19.0,
                                                    ["h"] = 733.0,
                                                    ["w"] = 510.0,
                                                    ["x"] = 1.0,
                                                },
                                                ["managed"] = {
                                                    [1] = {
                                                        ["geom"] = {
                                                            ["y"] = 0.0,
                                                            ["h"] = 732.0,
                                                            ["w"] = 508.0,
                                                            ["x"] = 1.0,
                                                        },
                                                        ["checkcode"] = 1.0,
                                                        ["level"] = 0.0,
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 6291468.0,
                                                        ["bottom"] = true,
                                                        ["sizepolicy"] = "full",
                                                    },
                                                },
                                                ["sizepolicy"] = "full",
                                                ["type"] = "WGroupCW",
                                                ["level"] = 0.0,
                                                ["name"] = "WGroupCW<1>",
                                                ["switchto"] = true,
                                            },
                                        },
                                    },
                                },
                            },
                        },
                        ["type"] = "WTiling",
                        ["level"] = 0.0,
                        ["name"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
            },
            [2] = {
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 768.0,
                    ["w"] = 1024.0,
                    ["x"] = 0.0,
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 768.0,
                            ["w"] = 1024.0,
                            ["x"] = 0.0,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue_center",
                        ["type"] = "WFrame",
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*",
                        ["mode"] = 0.0,
                    },
                },
                ["unnumbered"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["level"] = 1.0,
                ["name"] = "*scratchws*",
                ["sizepolicy"] = "full",
            },
        },
    },
}

